### ISSUE TITLE
Remove nodelet  from pointcloud_preprocessor

### ISSUE THREAD

**Issue by fred-apex-ai** [tier4/AutowareArchitectureProposal.iv#132]
## Motivation
Even after porting to ros2, the word nodelet survived in file names; e.g. there is `passthrough_filter_nodelet.cpp` but the node is registered as `PassThroughFilterComponent`. This is confusing.

## acceptance criterion

- [ ] names are consistent
- [ ] no more reference to nodelets, they don't exist in ros2

**Comment by wep21** [comment]
### Node list containing nodelet
- [ ] pointcloud preprocessor
- [ ] euclidean cluster
- [ ] roi cluster fusion
- [ ] tensorrt yolo
- [ ] traffic light classifier
- [ ] traffic light ssd fine detector
- [ ] traffic light roi visualizer
