### ISSUE TITLE
Issues in running GPS poser

### ISSUE THREAD

**Issue by fred-apex-ai** [tier4/AutowareArchitectureProposal.iv#137]
In porting `sensing_launch` in https://github.com/tier4/autoware_launcher.iv.universe/pull/14, I wrote this snippet of code when porting [this section](https://github.com/tier4/autoware_launcher.iv.universe/blob/master/sensing_launch/launch/aip_s1/gnss.launch#L9)

```
      <node pkg="ublox_gps" name="ublox" exec="ublox_gps_node" if="$(var launch_driver)">
        <remap from="ublox/fix" to="ublox/nav_sat_fix" />
          <arg var="parameters" value="$(find-pkg-share ublox_gps)/config/c94_f9p_rover"/>
      </node>
```

There are two problems:

## Runtime failure

```
[ublox_gps_node-1]   what():  U-Blox: Could not open serial port :/dev/ttyACM0 open: No such file or directory
[ERROR] [ublox_gps_node-1]: process has died [pid 31543, exit code -6, cmd '/home/frederik.beaujean/AutowareArchitectureProposal/install/ublox_gps/lib/ublox_gps/ublox_gps_node --ros-args -r __node:=ublox -r ublox/fix:=ublox/nav_sat_fix -r __ns:=/sensing/gnss'].
```

I suspect that's because I don't actually have the sensor connected to my laptop. Can somebody confirm this?

## Missing parameters

There is no config file `c94_f9p_rover` to be found in our repositories. I only found similarly named files `c94_m8*.yaml` in https://github.com/tier4/ublox/tree/master/ublox_gps/config and `m8u_rover.yaml` in the same directory. Does anyone know which file to choose? Or perhaps have a copy of the missing file?

**Comment by TakaHoribe** [comment]
@fred-apex-ai Not sure why, but `c94_f9p_rover.yaml` is not in the ros2 branch. I'll create a PR to port the file from master.

**Comment by TakaHoribe** [comment]
@fred-apex-ai Ahh, I understood. Please point the `tier4/master` branch, not `master` in autoware.proj.repos file. 
You can find it here.
https://github.com/tier4/ublox/blob/tier4/master/ublox_gps/config/c94_f9p_rover.yaml

**Comment by mitsudome-r** [comment]
Runtime failure seems to be due to no sensor attached so I think you can ignore it for now.
