### ISSUE TITLE
Incorrect encoding for image in HSV based traffic light classifier

### ISSUE THREAD

**Issue by VRichardJP** [tier4/AutowareArchitectureProposal.iv#297]
Hi,

I have found out that the HSV based traffic light classifier assume the image encoding is BGR: 
https://github.com/tier4/AutowareArchitectureProposal.iv/blob/2508e19f4da00eb48c554b30bf9bca4acbba0767/perception/traffic_light_recognition/traffic_light_classifier/src/color_classifier.cpp#L182

While the image is actually in RGB:
https://github.com/tier4/AutowareArchitectureProposal.iv/blob/2508e19f4da00eb48c554b30bf9bca4acbba0767/perception/traffic_light_recognition/traffic_light_classifier/src/nodelet.cpp#L85

As the result it leads to the classifier mistaking red light for green light.
The CNN based classifier does not have this issue.

The issue is present both in master and ros2 branch.

**Comment by taichiH** [comment]
Thank you for your information!
As you said I think this is a bug.
If you have a wrong input image visualized for debugging, could you share the image?

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
