### ISSUE TITLE
How to construct map to do localization?

### ISSUE THREAD

**Issue by chowkamlee81** [tier4/AutowareArchitectureProposal.iv#453]
How to construct map to do localization and traffic light detection? Kindly help

**Comment by taichiH** [comment]
I have some ideas.

PointCloud map is needed for localization. 
There are a lot of open source pointcloud map generation tools.
for example,
 - https://github.com/SMRT-AIST/interactive_slam

lanelet2 map is needed for planning and traffic light detection.(https://github.com/fzi-forschungszentrum-informatik/Lanelet2)
 - TierIV provide lanelet2 map build tool (https://tools.tier4.jp/feature/vector_map_builder/)
 
@mitsudome-r @TakaHoribe 
I think there may be same discussion on AWF. Do you have any ideas?

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
