### ISSUE TITLE
Cannot subscribe to rosbag topic when launch preprocessing.launch 

### ISSUE THREAD

**Issue by nisailhan** [tier4/AutowareArchitectureProposal.iv#474]
In order to concanate the lidar point cloud datas from the rosbag file I recorded before, I cannot subscribe to the topics in the preprocessing.launch file however I tried to many ways to subscribe. Anyone have an idea? 
Here's my launch file and rqt_graph: 
Note: I recorded the rosbag with only 2 lidars(you can see as /velodyne_points_01 and /velodyne_points_04) just for now and that's why I deleted if condition part from the launch file for concat filter and try to adapt my situation. 

Also when I launch the preprocessing.launch file I got this error: 
[ERROR] [1628676610.166239566]: Skipped loading plugin with error: XML Document '/home/nisa/workspace/AutowareArchitectureProposal.iv/install/traffic_light_ssd_fine_detector/share/traffic_light_ssd_fine_detector/traffic_light_ssd_fine_detector.xml' has no Root Element. This likely means the XML is malformed or missing..
[ INFO] [1628677513.596157724]: Initializing nodelet with 16 worker threads.
[ INFO] [1628677513.601915580]: waitForService: Service [/pointcloud_preprocessor/pcl_manager/load_nodelet] is now available.
[ WARN] [1628677518.640897647]: This node/nodelet subscribes topics only when subscribed.
[ WARN] [1628677518.724132091]: This node/nodelet subscribes topics only when subscribed.

```

<launch>
  <arg name="input_points_raw0" default="/velodyne_points_01"/>
  <arg name="input_points_raw1" default="/velodyne_points_04"/>
  <arg name="input_points_raw2" default=""/>
  <arg name="input_points_raw3" default=""/>
  <arg name="input_points_raw4" default=""/>
  <arg name="input_points_raw5" default=""/>
  <arg name="input_points_raw6" default=""/>
  <arg name="input_points_raw7" default=""/>
  <arg name="input_points_number" default="2"/>
  <arg name="output_points_raw" default="/points_raw/cropbox/filtered"/>
  <arg name="tf_output_frame" default="base_link"/>

  <!-- nodelet manager -->
  <group ns="pointcloud_preprocessor">
    <node pkg="nodelet" type="nodelet" name="pcl_manager" args="manager" output="screen" />

    <!-- concat filter -->
    <group if="$(eval input_points_number!=1)">
      <node pkg="nodelet" type="nodelet" name="concatenate_filter" args="load pcl/PointCloudConcatenateDataSynchronizer pcl_manager" output="screen">
        <rosparam param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1)]</rosparam>         
        <remap from="~output" to="points_raw/concatenated" />
        <param name="output_frame" value="$(arg tf_output_frame)" />
        <param name="approximate_sync" value="true" />
	
<!--        
<rosparam if="$(eval input_points_number==2)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1)]</rosparam>
        <rosparam if="$(eval input_points_number==3)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1), $(arg input_points_raw2)]</rosparam>
        <rosparam if="$(eval input_points_number==4)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1), $(arg input_points_raw2), $(arg input_points_raw3)]</rosparam>
        <rosparam if="$(eval input_points_number==5)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1), $(arg input_points_raw2), $(arg input_points_raw3), $(arg input_points_raw4)]</rosparam>
        <rosparam if="$(eval input_points_number==6)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1), $(arg input_points_raw2), $(arg input_points_raw3), $(arg input_points_raw4), $(arg input_points_raw5)]</rosparam>
        <rosparam if="$(eval input_points_number==7)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1), $(arg input_points_raw2), $(arg input_points_raw3), $(arg input_points_raw4), $(arg input_points_raw5), $(arg input_points_raw6)]</rosparam>
        <rosparam if="$(eval input_points_number==8)" param="input_topics" subst_value="true">[$(arg input_points_raw0), $(arg input_points_raw1), $(arg input_points_raw2), $(arg input_points_raw3), $(arg input_points_raw4), $(arg input_points_raw5), $(arg input_points_raw6), $(arg input_points_raw7)]</rosparam>-->
      </node>
    </group>

    <!-- crop box filter -->
    <node pkg="nodelet" type="nodelet" name="crop_box_filter_mesurement_range" args="load pointcloud_preprocessor/crop_box_filter_nodelet pcl_manager" output="log">
      <remap if="$(eval input_points_number==1)" from="~input" to="$(arg input_points_raw0)" />
      <remap if="$(eval input_points_number!=1)" from="~input" to="points_raw/concatenated" />
      <remap from="~output" to="$(arg output_points_raw)" />
      <rosparam>
        min_x: -200.0
        max_x: 1000.0
        min_y: -50.0
        max_y: 50.0
        min_z: -2.0
        max_z: 3.0
        negative: False
      </rosparam>
      <param name="input_frame" value="$(arg tf_output_frame)" />
      <param name="output_frame" value="$(arg tf_output_frame)" />
    </node>
  </group>
</launch>
```

![Screenshot from 2021-08-11 13-08-16](https://user-images.githubusercontent.com/58118577/129011301-68056cac-83fc-47a5-b18a-d6ed926972f4.png)

**Comment by nisailhan** [comment]
[Update] I fixed this error: [ERROR] [1628676610.166239566]: Skipped loading plugin with error: XML Document '/home/nisa/workspace/AutowareArchitectureProposal.iv/install/traffic_light_ssd_fine_detector/share/traffic_light_ssd_fine_detector/traffic_light_ssd_fine_detector.xml' has no Root Element. This likely means the XML is malformed or missing..

**Comment by taichiH** [comment]
@nisailhan 
Hi! Thank you for the contibution!

> I cannot subscribe to the topics in the preprocessing.launch file however I tried to many ways to subscribe. 

Did you mean you can't subscribe output of concatenate_filter topic by echo command?
```
rostopic echo /pointcloud_preprocessor/points_raw/concatenated
```

I have few questions.
1. Is there`base_link` frame in your tf tree? If not, please set valid tf frame to `tf_output_frame`. 
2. timestamps of `velodyne_points_01` and `velodyne_points_04` are enough close?
3. Could you attach full console output for more information?

**Comment by nisanurilhan** [comment]
> Did you mean you can't subscribe output of concatenate_filter topic by echo command?
I mean that I cannot subscribe to /velodyne_points_01 and /velodyne_points_04 from concatenate_filter node. I want that concatenate_filter node must be subscribe to bag file's point cloud topics (in this case /velodyne_points_01, /velodyne_points_04), after that crop_box_filter node should also  subscribe to the concatenate node's output topics (in this case /points_raw/concatenated) 
 
> 1. Is there`base_link` frame in your tf tree? If not, please set valid tf frame to `tf_output_frame`.
Yes it is base_link
> 2. timestamps of `velodyne_points_01` and `velodyne_points_04` are enough close?
Yes it is enough I guess. 
> 3. Could you attach full console output for more information?
nisa@nisa:~/workspace/AutowareArchitectureProposal.iv$ roslaunch '/home/nisa/workspace/AutowareArchitectureProposal.iv/sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/preprocessor.launch' 
... logging to /home/nisa/.ros/log/715939f4-fb32-11eb-8e00-d8f883d8ae87/roslaunch-nisa-6354.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nisa:40823/

SUMMARY
========

PARAMETERS
 * /pointcloud_preprocessor/concatenate_filter/approximate_sync: True
 * /pointcloud_preprocessor/concatenate_filter/input_topics: ['/velodyne_point...
 * /pointcloud_preprocessor/concatenate_filter/output_frame: base_link
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/input_frame: base_link
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/max_x: 1000.0
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/max_y: 50.0
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/max_z: 3.0
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/min_x: -200.0
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/min_y: -50.0
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/min_z: -2.0
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/negative: False
 * /pointcloud_preprocessor/crop_box_filter_mesurement_range/output_frame: base_link
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /pointcloud_preprocessor/
    concatenate_filter (nodelet/nodelet)
    crop_box_filter_mesurement_range (nodelet/nodelet)
    pcl_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[pointcloud_preprocessor/pcl_manager-1]: started with pid [6384]
process[pointcloud_preprocessor/concatenate_filter-2]: started with pid [6385]
process[pointcloud_preprocessor/crop_box_filter_mesurement_range-3]: started with pid [6386]
[ INFO] [1628747970.831990126]: Loading nodelet /pointcloud_preprocessor/crop_box_filter_mesurement_range of type pointcloud_preprocessor/crop_box_filter_nodelet to manager pcl_manager with the following remappings:
[ INFO] [1628747970.832637708]: /pointcloud_preprocessor/crop_box_filter_mesurement_range/input -> /pointcloud_preprocessor/points_raw/concatenated
[ INFO] [1628747970.832687960]: /pointcloud_preprocessor/crop_box_filter_mesurement_range/output -> /points_raw/cropbox/filtered
[ INFO] [1628747970.833592585]: waitForService: Service [/pointcloud_preprocessor/pcl_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1628747970.848248277]: Initializing nodelet with 16 worker threads.
[ INFO] [1628747970.854087964]: waitForService: Service [/pointcloud_preprocessor/pcl_manager/load_nodelet] is now available.
[ WARN] [1628747975.946754205]: This node/nodelet subscribes topics only when subscribed.
[ WARN] [1628747976.040929926]: This node/nodelet subscribes topics only when subscribed.

**Comment by nisailhan** [comment]
>> Did you mean you can't subscribe output of concatenate_filter topic by echo command?

I mean that I cannot subscribe to /velodyne_points_01 and /velodyne_points_04 from concatenate_filter node. I want that concatenate_filter node must be subscribe to bag file's point cloud topics (in this case /velodyne_points_01, /velodyne_points_04), after that crop_box_filter node should also subscribe to the concatenate node's output topics (in this case /points_raw/concatenated)

>> 1. Is there`base_link` frame in your tf tree? If not, please set valid tf frame to `tf_output_frame`.
Yes it is base_link
>> 2. timestamps of `velodyne_points_01` and `velodyne_points_04` are enough close?
Yes it is enough I guess.
>> 3. Could you attach full console output for more information?
nisa@nisa:~/workspace/AutowareArchitectureProposal.iv$ roslaunch '/home/nisa/workspace/AutowareArchitectureProposal.iv/sensing/preprocessor/pointcloud/pointcloud_preprocessor/launch/preprocessor.launch'
... logging to /home/nisa/.ros/log/715939f4-fb32-11eb-8e00-d8f883d8ae87/roslaunch-nisa-6354.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://nisa:40823/

SUMMARY
PARAMETERS

/pointcloud_preprocessor/concatenate_filter/approximate_sync: True
/pointcloud_preprocessor/concatenate_filter/input_topics: ['/velodyne_point...
/pointcloud_preprocessor/concatenate_filter/output_frame: base_link
/pointcloud_preprocessor/crop_box_filter_mesurement_range/input_frame: base_link
/pointcloud_preprocessor/crop_box_filter_mesurement_range/max_x: 1000.0
/pointcloud_preprocessor/crop_box_filter_mesurement_range/max_y: 50.0
/pointcloud_preprocessor/crop_box_filter_mesurement_range/max_z: 3.0
/pointcloud_preprocessor/crop_box_filter_mesurement_range/min_x: -200.0
/pointcloud_preprocessor/crop_box_filter_mesurement_range/min_y: -50.0
/pointcloud_preprocessor/crop_box_filter_mesurement_range/min_z: -2.0
/pointcloud_preprocessor/crop_box_filter_mesurement_range/negative: False
/pointcloud_preprocessor/crop_box_filter_mesurement_range/output_frame: base_link
/rosdistro: melodic
/rosversion: 1.14.11
NODES
/pointcloud_preprocessor/
concatenate_filter (nodelet/nodelet)
crop_box_filter_mesurement_range (nodelet/nodelet)
pcl_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[pointcloud_preprocessor/pcl_manager-1]: started with pid [6384]
process[pointcloud_preprocessor/concatenate_filter-2]: started with pid [6385]
process[pointcloud_preprocessor/crop_box_filter_mesurement_range-3]: started with pid [6386]
[ INFO] [1628747970.831990126]: Loading nodelet /pointcloud_preprocessor/crop_box_filter_mesurement_range of type pointcloud_preprocessor/crop_box_filter_nodelet to manager pcl_manager with the following remappings:
[ INFO] [1628747970.832637708]: /pointcloud_preprocessor/crop_box_filter_mesurement_range/input -> /pointcloud_preprocessor/points_raw/concatenated
[ INFO] [1628747970.832687960]: /pointcloud_preprocessor/crop_box_filter_mesurement_range/output -> /points_raw/cropbox/filtered
[ INFO] [1628747970.833592585]: waitForService: Service [/pointcloud_preprocessor/pcl_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1628747970.848248277]: Initializing nodelet with 16 worker threads.
[ INFO] [1628747970.854087964]: waitForService: Service [/pointcloud_preprocessor/pcl_manager/load_nodelet] is now available.
[ WARN] [1628747975.946754205]: This node/nodelet subscribes topics only when subscribed.
[ WARN] [1628747976.040929926]: This node/nodelet subscribes topics only when subscribed.

**Comment by taichiH** [comment]
> I want that concatenate_filter node must be subscribe to bag file's point cloud topics (in this case /velodyne_points_01, /velodyne_points_04), after that crop_box_filter node should also subscribe to the concatenate node's output topics (in this case /points_raw/concatenated)

You're right.

Sorry, I don't have enough information for debug. Could you describe more detail?

If you want to test more simply you'd better to use standalone node but nodelet. Please replace `load` to `standalone` in the launch file.
`args="load pcl/PointCloudConcatenateDataSynchronizer pcl_manager"` -> `args="standalone pcl/PointCloudConcatenateDataSynchronizer pcl_manager"`

I think you also don't need `crop_box_filter` so you can remove it.

**Comment by taichiH** [comment]
@nisailhan 
By the way, this repository doesn't have enough test and has less mentainer because the purpose of this repository is just to propose to architecture to the [AWF](https://www.autoware.org).

So if you want to use concatenate_filter function you have two choice.
1. You can use Autoware.AI that is stable version of Autoware and work on ROS1 environment. Please refet to [instalation guide ](https://github.com/Autoware-AI/autoware.ai) and [corresponding function part](https://github.com/Autoware-AI/core_perception/blob/master/points_preprocessor/launch/points_concat_filter.launch) . Be careful, Autoware.AI has already finished development phase.
2. Secod choise is Autoware.Auto that is new version of Autoware. Autoware.Auto is developing now based on Autoware.AI and some part is inspird by this repository. You need ROS2 environment to use Autoware.Auto. Please refer to [instalation guide](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/installation.html) and [concatenate_filter](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/tree/master/src/perception/filters/point_cloud_fusion_nodes)

**Comment by nisanurilhan** [comment]
>> `args="load pcl/PointCloudConcatenateDataSynchronizer pcl_manager"` -> `args="standalone pcl/PointCloudConcatenateDataSynchronizer pcl_manager"`

I made changes in launch file as you said but nothing has changed as you can see below. 
![Screenshot from 2021-08-16 10-35-15](https://user-images.githubusercontent.com/80104573/129527788-57c8905f-a5bb-4b9e-8d62-d0c613139932.png)

>>By the way, this repository doesn't have enough test and has less mentainer because the purpose of this repository is just to propose to architecture to the AWF.

I know that this repository is proposal just for now but at the same time I'm aware of that some awkwark parts of the codes are fixed in your this version.  I can describe if you tell me what details I should provide. 

Thank you a lot for your help

**Comment by nisailhan** [comment]
>args="load pcl/PointCloudConcatenateDataSynchronizer pcl_manager" -> args="standalone pcl/PointCloudConcatenateDataSynchronizer pcl_manager"

I made changes in launch file as you said but nothing has changed as you can see in the attachment
![Screenshot from 2021-08-16 10-35-15](https://user-images.githubusercontent.com/58118577/129529162-0b86c041-669e-4d0c-be4a-70bad5b465bc.png)


>By the way, this repository doesn't have enough test and has less mentainer because the purpose of this repository is just to propose to architecture to the AWF.

I know that this repository is proposal just for now but at the same time I'm aware of that some awkwark parts of the codes are fixed in your this version. I can describe if you tell me what details I should provide.

Thank you a lot for your help

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
