### ISSUE TITLE
(.autoポーティング) Trajectoryサイズのcapacity(=100)の調整

### ISSUE THREAD

**Issue by takayuki5168** [tier4/AutowareArchitectureProposal.iv#486]
@TakaHoribe @rej55 cc @yukkysaito @kenji-miyake 

一旦ビルドを通すためにcapcity=100で進めて最後に調整する

capacity=100で問題ありそうなパッケージ
- obstacle avoidance planner

**Comment by kmiya** [comment]
Here is a public repository (and AWF members may check here). Might be better to use English instead of Japanese?

**Comment by mitsudome-r** [comment]
Closing this as we are archiving the repository: https://github.com/tier4/AutowareArchitectureProposal.proj#update-20220916
