### ISSUE TITLE
how to convert darknet yolov4 to ONNX used in tensorrt_yolo?

### ISSUE THREAD

**Issue by lgz897369617** [tier4/AutowareArchitectureProposal.iv#523]
I tried many methods on the Internet and failed, thank you very much

**Comment by lgz897369617** [comment]
@daisuke-hoshina

**Comment by lgz897369617** [comment]
@Daisuke Nishimatsu

**Comment by kenji-miyake** [comment]
Thank you for asking your question.
However, I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
