### ISSUE TITLE
vehicle_info_util.cpp: return node.declare_parameter<T>(name); error

### ISSUE THREAD

**Issue by zazgf** [tier4/AutowareArchitectureProposal.iv#618]
vehicle_info_util.cpp: In instantiation of ‘T {anonymous}::getParameter(rclcpp::Node&, const string&) [with T = double; std::string = std::__cxx11::basic_string<char>]’:
vehicle_info_util.cpp:44:75:   required from here
vehicle_info_util.cpp:29:44: error: no matching function for call to ‘rclcpp::Node::declare_parameter<double>(const string&)’
   29 |       return node.declare_parameter<T>(name);
      |                                            ^
In file included from /opt/ros/foxy/include/rclcpp/node.hpp:1224,
                 from /opt/ros/foxy/include/rclcpp/executors/single_threaded_executor.hpp:28,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:22,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
                 from /home/autoware/src/autoware/AutowareArchitectureProposal.iv-main/vehicle/util/vehicle_info_util/include/vehicle_info_util/vehicle_info_util.hpp:20,
                 from /home/autoware/src/autoware/AutowareArchitectureProposal.iv-main/vehicle/util/vehicle_info_util/src/vehicle_info_util.cpp:15:
/opt/ros/foxy/include/rclcpp/node_impl.hpp:157:1: note: candidate: ‘auto rclcpp::Node::declare_parameter(const string&, const ParameterT&, const ParameterDescriptor&, bool) [with ParameterT = double; std::string = std::__cxx11::basic_string<char>; rcl_interfaces::msg::ParameterDescriptor = rcl_interfaces::msg::ParameterDescriptor_<std::allocator<void> >]’
  157 | Node::declare_parameter(
      | ^~~~
/opt/ros/foxy/include/rclcpp/node_impl.hpp:157:1: note:   candidate expects 4 arguments, 1 provided
make[2]: *** [CMakeFiles/vehicle_info_util.dir/build.make:63: CMakeFiles/vehicle_info_util.dir/src/vehicle_info_util.cpp.o] Error 1`

**Comment by kenji-miyake** [comment]
Thank you for asking your question.
However, I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

**Comment by zazgf** [comment]
> Thank you for asking your question. However, I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

Still thank you

**Comment by zazgf** [comment]
I fixed it with 
`T default_value;
 return node.declare_parameter(name,default_value);`
This is a ros problem.
