### ISSUE TITLE
About concatenate_data logic improvement

### ISSUE THREAD

**Issue by taichiH** [tier4/AutowareArchitectureProposal.iv#790]
### overview
@0x126 @miursh @aohsato @yukkysaito @YamatoAndo 
I think that the existing concat filter is comlicated to implement and is prone to unexpected bugs. So I came up with a simpler implementation. Please comment for this issue!

### difference
- Existing logic
  - Basically wait until all topics are available except in some cases. If the same topic is subscribed multiple times before all the topics are available, the timer will start from there, and if the topics are not available by the timeout, the remaining topics will be combined and published at that time.
- New logic
  - The topics subscribed within the timeout are combined and published at that time. If all topics are not available at time limit, the remaining topics will be combined and published at that time. (please refer to below image.)

![concatenate_data-new](https://user-images.githubusercontent.com/22497720/147212202-a9267fdd-aa25-4abb-bfd3-30467f2e22ea.jpg)

### Limitation
The current implementation does something like case1. For example, data for annotation should be conbined in consideration of shutter timing. To do this, for example, searching close time stamp topics from topic queue is one of the idea. However, the interval between topics is actually short, so I think that linear interpolation is sufficient even in case2.

#### case1
Since the conventional logic does not consider the shutter timing, it will combine topics with different shutter timings as shown in the figure below.
![concatenate_data-not-consider-shutter-timing](https://user-images.githubusercontent.com/22497720/147217785-81cae22c-2944-47f6-8d2b-fc3a5538f201.jpg)

#### case2
Ideally, it is better to combine topics with the same shutter timing like this.
![concatenate_data-consider-shutter-timing](https://user-images.githubusercontent.com/22497720/147217775-85cb7f60-9f70-44b7-a5d2-234e2f58dcb4.jpg)

**Comment by mitsudome-r** [comment]
Closing this as we are archiving the repository: https://github.com/tier4/AutowareArchitectureProposal.proj#update-20220916
