### ISSUE TITLE
About CenterPoint Encoder Backend Choice

### ISSUE THREAD

**Issue by OrcunCanDeniz** [tier4/AutowareArchitectureProposal.iv#801]
I was wondering why did you choose to run centerpoint voxel encoder module on Torch instead of TRT ?

**Comment by mitsudome-r** [comment]
Thank you for posting the issue, but we are closing this as we are archiving the repository: https://github.com/tier4/AutowareArchitectureProposal.proj#update-20220916.

Most of the packages are integrated in [Autoware.Universe](https://github.com/autowarefoundation/autoware.universe), so please consider continuing discussion there.
