### ISSUE TITLE
MPC weight problem

### ISSUE THREAD

**Issue by schweinebauch** [tier4/AutowareArchitectureProposal.iv#802]
Hey guys
In mpc.cpp file does anyone know how to derivate these two functions 'addSteerWeightR' and 'addSteerWeightF'? I can not understand these two functions.

Looking forward to receiving help!

**Comment by mitsudome-r** [comment]
Thank you for posting the issue, but we are closing this as we are archiving the repository: https://github.com/tier4/AutowareArchitectureProposal.proj#update-20220916.

Most of the packages are integrated in [Autoware.Universe](https://github.com/autowarefoundation/autoware.universe), so please consider continuing discussion there.
