### ISSUE TITLE
About CenterPoint training and export to ONNX

### ISSUE THREAD

**Issue by BrokenVoodooDoll** [tier4/AutowareArchitectureProposal.iv#807]
The ReadME of the lidar_centerpoint module reads that you're training the model using mmdetection3d. How did you export it to ONNX then? And which configuration of the CenterPoint in mmdetection3d is used?

**Comment by mitsudome-r** [comment]
Thank you for posting the issue, but we are closing this as we are archiving the repository: https://github.com/tier4/AutowareArchitectureProposal.proj#update-20220916.

Most of the packages are integrated in [Autoware.Universe](https://github.com/autowarefoundation/autoware.universe), so please consider continuing discussion there.
